name: Auto-update-dae-rules
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 1'  
jobs:
  update-dat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 创建目录并下载文件
        run: |
          # 保存目录：files/usr/share/dae
          mkdir -p files/usr/share/dae
          
          wget -O files/usr/share/dae/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          wget -O files/usr/share/dae/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          
          ls -lh files/usr/share/dae/

      - name: 提交更新到仓库
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add files/usr/share/dae/*
          git commit -m "Auto update dae geoip & geosite [$(date +'%Y-%m-%d')]" || exit 0
          git push
